### PR TITLE
improve UGRID support

### LINKED ISSUE #29: Implementation missing for UGRID start_index attribute
The UGRID standard allows node connectivities to be specified as zero-based or one-based.  The base is indicated by the attribute `start_index` of the connectivity variable.  

#### Code Sample, a copy-pastable example if possible

```
	int mesh_element_node_connectivity(mesh_element, ungridded00004) ;
		mesh_element_node_connectivity:long_name = "mesh_element_node_connectivity" ;
		mesh_element_node_connectivity:standard_name = "face_node_connectivity" ;
		mesh_element_node_connectivity:start_index = 1;
```

#### Problem description

Currently, `psyplot` seems to handle only zero-based connectivities and disregards this attribute.

On the above example, an index-out-of-bounds error is thrown.

#### Workaround

As a workaround, you can decrease the index by one

```python
    ds['mesh_element_node_connectivity'][:] = ds['mesh_element_node_connectivity'][:] - 1
    ds['mesh_element_node_connectivity'].__setitem__('start_index',0)

```

#### NOTE
This is a bug report.

For requesting new features, use [this template](https://github.com/psyplot/psyplot/issues/new?template=new_feature.md&title=NEW+FEATURE:).

For changing existing features, use [this template](https://github.com/psyplot/psyplot/issues/new?template=change_feature.md&title=CHANGE+FEATURE:).

### LINKED ISSUE #32: NEW FEATURE: Visualization of UGRID elements defined on the nodes
#### Summary
Within the UGRID conventions it is possible to defined variables to live on the _nodes_, rather than the _faces_. Within psyplot, we do visualize them at the the moment, but silently this provides wrong results.

#### Reason
It should be possible to visualize these elements, too.

#### Detailed explanation
Within the `get_cell_node_coord` method of the UGRID decoder, we generate triangles using a delauney triangulation. 

https://github.com/psyplot/psyplot/blob/36a23ce964d58e41468fd1f97188b75454c14b7d/psyplot/data.py#L1807

I think this is fine for now as we do not have generic methods to generate grids from the nodes. What grid is the best is a very scientific question and should rather be answered by a custom decoder class for the data.

None the less, the current implementation in psy-maps (and psy-simple) is wrong. In the [`_polycolor`](https://github.com/psyplot/psy-maps/blob/34ad17e7d9ea55d4ebe8dfd04bb7963477ccc683/psy_maps/plotters.py#L1729) method, we say `transformed, array=arr.ravel()`. For variables on a node however, this does not generate correct results because the length of the `array` (which is the same as the number of nodes) is not the same as for `transformed`, which has the length of the number of triangles.

So `array` should actually be the mean of the nodes for each generated face element (i.e. for each generated triangle).

#### Examples
matplotlibs `tripcolor` method is doing exactly this: https://github.com/matplotlib/matplotlib/blob/e097bf4baf8f275fda91f224b537076caf17dd91/lib/matplotlib/tri/tripcolor.py#L108

ping @platipodium

### PR DESCRIPTION
**Pull request by Chilipp**
with this PR, we implement the ability to visualize variables on nodes
and edges via the dual mesh.
We base the UGRID decoder on the gridded package, particularly on
https://github.com/NOAA-ORR-ERD/gridded/pull/61 and https://github.com/NOAA-ORR-ERD/gridded/pull/62

closes #29
closes https://github.com/psyplot/psy-maps/issues/32

 - [ ] Tests added (for all bug fixes or enhancements)
 - [ ] Tests passed (for all non-documentation changes)
 - [ ] Fully documented, including `CHANGELOG.rst` for all changes

### CODE REVIEW

**Comment by Chilipp** [comment]
@platipodium, I'd highly appreciate if you test this implementation with your data. For me, everything works out of the box with the `schout_5.nc` file you sent me today.

Note that you have to install the gridded package from https://github.com/NOAA-ORR-ERD/gridded/pull/62 and this branch. You can do this for instance via

```
pip install -U git+https://github.com/Chilipp/gridded@dual_node_mesh git+https://github.com/Chilipp/psyplot@ugrid 
```

**Comment by platipodium** [comment]
Works for me regarding both issues

- start_index
- dual mesh

Other things are still not perfect, but should go to a different bug report.  Thanks for fixing these issues so quickly.

**Comment by Chilipp** [comment]
thanks a lot @platipodium! I need to wait for the decisions in the `gridded` PRs, but I hope they will come soon

**Comment by Chilipp** [comment]
closing this PR, see https://codebase.helmholtz.cloud/psyplot/psyplot/-/merge_requests/31

**Pull request closed without merging**
